name: Deploy the app on VPS

on:
  push:
    branches: ['deploy']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Deploy to VPS
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ubuntu@ec2-35-180-103-5.eu-west-3.compute.amazonaws.com
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: /root/my-deployment
          stack_file_name: docker-compose.yml
          args: up -d