name: Node.js Release

on:
  push:
    branches: ['main']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devopsproject:${{ github.sha }}

      - 
        name: Update Version In Checked-Out Code
        run: |
          sed -i "s@\(.*image: ${{secrets.DOCKERHUB_USERNAME}}/devopsproject:\).*@\1${{ github.sha }}@" docker-compose.yml
      # - 
      #   name: Commit The New Image Reference
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Deploy new image ${{ github.sha }}
      #     branch: deploy
      #     commit_options: '--no-verify --signoff'
      #     repository: .
      #     commit_user_name: Deploy Bot
      #     commit_user_email: deploy-bot@insat.tn
      #     commit_author: Deploy Bot <deploy-bot@insat.tn>
      - 
        name: Deploy to VPS
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ubuntu@ec2-35-180-103-5.eu-west-3.compute.amazonaws.com
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: /home/ubuntu/devops-project
          stack_file_name: docker-compose.yml
          args: up -d